# _config_dev.yml - Dev environment configs and overrides

show_drafts: true

# Accepts connections on port 4000 from any source
host: localhost
port: 4000

# Don't compress SASS output
sass:
  style: full

url: http://locahost:4000
